import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import { WishlistProvider } from "@/context/WishlistContext";
import Header from "@/components/Header";
import "../styles/globals.css";

const fira = Fira_Sans({
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className}>
        <WishlistProvider>
          <div className="wrapper-layout">
            <Header />
            {children}
          </div>
        </WishlistProvider>
      </body>
    </html>
  );
}
